# Site settings
about:
  elleTech:
    name: "ElleTech"
    description: "Le blog de Christelle Malala"
    url: ""
  vexxia:
    name: "Vexxia"
    description: "A web development and marketing agency."
    url: ""

url:
  assets: "https://elletechblog.github.io/assets"
  development: "http://localhost:4000"
  beta: "https://ellemalala.github.io/elletechblog-beta"
  production: "https://elletechblog.github.io"

favicons:
  apple-touch-icon: [180, 167, 152, 144, 120, 76, 72, 60, 57]
  apple-touch-icon-precomposed: [152, 144, 120, 72, 57, 32]
  icon: [196, 128, 32, 16]
  manifest: [192, 168, 144, 152, 128, 96, 72, 48]
  msapplication-square: [310, 150, 70]

# Build settings
encoding: utf-8
markdown: kramdown
generator: "Jekyll 3.1.6"